package com.company;

import java.util.concurrent.ThreadLocalRandom;

public class singleChoiceQuestion extends Question{
    private final String[] questionBank = {"True or False: America is a Democracy", "Which of the following is NOT a" +
            " data type in Java", "True or False: Binary is 0 1 or 2"};
    // Stored the questions and responses in String arrays to be able to easily print them and to have a unique index
    // for each question and response
    private final String[] responses = {"(0) True\n(1) False\n", "(0) String\n(1) Int\n(2) char\n(3) twin\n", "(0) True\n" +
            "(1) False\n"};

    // Returns the single choice question generated by the random index in Question
    public String generateQuestion(int index) {
        return questionBank[index];
    }

    // Returns the single choice response generated by the random index in Question
    public String generateResponses(int index) { // Returns the response generated by the random index in Question
        return responses[index];
    }
}
